experiment_name: firn_default
runs_dir: runs

model:
  hidden_layers: [128, 128, 128, 128]
  dtype: float32

training:
  optimizer: adam       # run this phase first
  epochs: 10000
  learning_rate: 1.0e-3
  n_interior: 4096
  n_boundary: 256
  n_initial: 256
  # (optionally add a scheduler in code if you like)

loss:
  w_pde: 2.0
  w_bc: 5.0
  w_ic: 1.0


problem:
  name: firn
  t_min: 0.0
  t_max: 1.0
  z_min: 0.0
  z_max: 1.0
